### PR TITLE
Implement Ultimate Guitar scraper

### PR DESCRIPTION
**Pull request by doorlay**
Implement the Ultimate Guitar scraper, written in Python.

Given a song name, artist name, and either "tab" or "chord", the scraper will return the HTML for a particular song's tab.

### CODE REVIEW

**Comment by esauerbo** [comment]
Really great work! In future versions it would be good to work on improving the speed.

**Comment by doorlay** [comment]
@esauerbo Thanks! I'm going to look into why specifically the runtime is so long.

**Comment by Nathanllee1** [comment]
Looks solid, very pythonic :+1:

**Comment by doorlay** [comment]
@Nathanllee1 Thanks! Appreciate it

**Comment by BSilton26** [comment]
Looks good, I appreciate you including comments ✅

**Comment by doorlay** [comment]
@BSilton26 Thanks! I'll make sure to keep up the comment-coverage in future CR's

**Pull request merged**
